kind: Service
apiVersion: v1
metadata:
  name: sftp-svc
  namespace: sftp
  labels:
    environment: production
spec:
  type: "LoadBalancer"
  ports:
  - name: "22"
    # don't use the default part, to allow the machine this runs on to be accessed using ssh
    port: 22
    targetPort: 22
  selector:
    app: sftp
status:
  loadBalancer: {}