kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sftp-route
  namespace: b2bi-prod
  annotations:
    argocd.argoproj.io/sync-wave: "280"
spec:
  host: sftp.apps.pawaro.eastus.aroapp.io
  to:
    kind: Service
    name: sftp-svc
    weight: 100
  port:
    targetPort: "22"
  wildcardPolicy: None
